# 统一身份认证区
[nju]
username = '0412007'
password = 'V1ews0n1c'

# 邮件区
[email]
email         = '19708876912@163.com'
token         = 'JQJJDUZSXVKLLGAP'
preview_email = '231220088@smail.nju.edu.cn'


# 表格api
[table]
server    = 'https://table.nju.edu.cn'
api_token = 'aeade84e27bb0cf7d43c213b570bb9ae641334ec'


# 邮件机器人
[mailbot]
port = 8080

[ocr]
# token = '-aiEOVLTyt9yoOmq6cLvYrKejQGimynQieo3IjO1k44'
token = 'TA6djdhm0NC1ROb8KJLaxG7WSf2ycfBZ46Lg7Tc0e5c'
