# 统一身份认证区
[nju]
username = '0412007'
password = 'V1ews0n1c'

# 邮件区
[email]
email         = '1398881912@qq.com'
token         = 'snocsimxfjvchcci'
preview_email = '231220088@smail.nju.edu.cn'


# 表格api
[table]
server    = 'https://table.nju.edu.cn'
api_token = '56128d59ebfaf66936a14228cd92351ef100fd36'


# 邮件机器人
[mailbot]
port = 8080

[ocr]
# token = '-aiEOVLTyt9yoOmq6cLvYrKejQGimynQieo3IjO1k44'
token = 'TA6djdhm0NC1ROb8KJLaxG7WSf2ycfBZ46Lg7Tc0e5c'
