# 统一身份认证区
[nju]
username = '0412007'
password = 'V1ews0n1c'

# 邮件区
[email]
email = '发送邮件的邮箱'
token = '发送邮件的邮箱授权码'



# 表格api
[table]
server    = 'https://table.nju.edu.cn'
api_token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkdGFibGVfdXVpZCI6IjU3NmE0NGJmLTlkMjItNDllMC1iNjI0LTYzNzMzNjk3NDQ0MSIsImFwcF9uYW1lIjoiMTh3cS5weSIsImV4cCI6MTcxMTc0MDM4Nn0.pNAbI5Bz9YblcVzvPR3Avo9gqraBFGixVn5xKjVusqo'


# 邮件机器人
[mailbot]
port = 8080

[ocr]
# token = '-aiEOVLTyt9yoOmq6cLvYrKejQGimynQieo3IjO1k44'
token = 'TA6djdhm0NC1ROb8KJLaxG7WSf2ycfBZ46Lg7Tc0e5c'
